config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "events#index"
  get "/events/create", to: 'events#create'
  resources :events
  resources :users, only: [:show]
  get 'users/:id/show', to: "users#show", as: :attended_events

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  put 'events/:id/attend', to: 'events#attend', as: 'attend'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attended_event.rb
class AttendedEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, :body, presence: true

  scope :future, ->  { where('date < ?', Date.today) }
  scope :past, -> {where('date >= ?', Date.today)}

  def add_attendee(user)
    self.attendees << user
  end

  belongs_to :creator, foreign_key: "user_id", class_name: "User", primary_key: :id
  has_many :attended_events
  has_many :attendees, through: :attended_events, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :created_events, foreign_key: "user_id", class_name:"Event"
  has_many :attended_events
  has_many :events_attended, through: :attended_events, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])


  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end
  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event, notice: "Your event was created"
    else
      render :new
    end
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event, notice: "Your event was updated"
    else
      render :edit
    end

  end

  def attend
    @event = Event.find(params[:id])

    if @event.attendees.none? {|user| user.email == current_user.email}
      @event.add_attendee(current_user)
      redirect_to event_path(@event)
    end

  end

  def past

  end

  def future

  end

  private

  def event_params
    params.require(:event).permit(:title, :body, :date)
  end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with model: @event do |form| %>

  <% if @event.errors.any? %>
    <ul>
      <% @event.errors.full_messages.each do |error| %>
        <li> <%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="field"> <br />
      <%= form.text_field :title, placeholder: "Event Title", required: true%>
  </div>

  <div class="field"> <br />
    <%= form.text_field :body, placeholder: "Event Description", required: true %>
  </div>

  <div class="field"> <br />
    <%= form.date_field :date, placeholder: "Event Date" , required: true %>
  </div>

  <div class="field"> <br />
    <%= form.submit "Create" %>
  </div>

<% end %>

app/views/events/index.html.erb
<h1>All Events</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"> Title </th>
      <th scope="col"> Description </th>
      <th scope="col">Details</th>
    </tr>
  </thead>
  <% @events.each_with_index do |event,index| %>
    <tr>
      <td scope="row"> <%= index + 1 %> </td>
      <td > <%= event.title %></td>
      <td> <%= event.body %></td>
      <td> <%= link_to "Event Details", event_path(event.id)  %></td>
    </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<h1> Create Events </h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<h1>Event Details</h1>
<h2><%= @event.title %></h2>

<p> This event was made by <%= @event.creator.first_name %></p>
<br>
<p> Would you like to attend?</p>

<%= button_to 'Attend', attend_path(@event), method: :put %> <br>

<h3>Current Attendees </h3>

<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col"> Email </th>
    <th scope="col"> First Name </th>
    <th scope="col"> Last Name </th>
    <th scope="col"> Update</th>
  </tr>
  </thead>
  <% @event.attendees.each_with_index do |attendee,index| %>
    <tr>
      <td scope="row"> <%= index + 1 %> </td>
      <td > <%= attendee.email %></td>
      <td > <%= attendee.first_name %></td>
      <td > <%= attendee.last_name %></td>
      <td> Placeholder to update attendee</td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>

    <nav class="navbar navbar-expand-lg bg-dark bg-body-tertiary" data-bs-theme="dark"  >
      <div class="container-fluid">
        <!-- <a class="navbar-brand" href="<%= root_path %>">Private Events</a> -->

        <%= link_to "Private Events",root_path, class:"navbar-brand" %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Home",root_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <% if user_signed_in? %>

              <li class="nav-item">
                <%= link_to "Create Event",new_event_path, class:"nav-link" %>
              </li>

              <li class="nav-item">
                <%= link_to "Attended Events", attended_events_path(current_user.id), class:"nav-link" %>
              </li>

              <li class="nav-item">
                <%= link_to "Edit Profile",edit_user_registration_path, class:"nav-link" %>
              </li>

              <li class="nav-item">
                <%= link_to "Sign-out", destroy_user_session_path, :method => :delete, class:"nav-link" %>
              </li>


            <% else %>

              <li class="nav-item">
                <%= link_to "Sign-in",new_user_session_path , class:"nav-link" %>
              </li>

              <li class="nav-item">
                <%= link_to "Sign-up",new_user_registration_path , class:"nav-link" %>
              </li>



            <% end %>

            </li>

          </ul>
        </div>
      </div>
    </nav>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div style="margin: 25px">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
 <h1>Attended Events</h1>

  <br>
  <br>

 <h2> Upcoming Events </h2>

 <table class="table">
   <thead>
   <tr>
     <th scope="col">#</th>
     <th scope="col"> Title </th>
     <th scope="col"> Description </th>
     <th scope="col"> Date </th>
     <th scope="col"> Attendee Count </th>
     <th scope="col"> Update</th>
   </tr>
   </thead>

  <% Event.future.find do |event| %>

    <% event.attendees.each do |attendee| %>
      <% if attendee.email == @user.email %>

            <tr>
              <% number = 1 %>
              <td scope="row"> <%= number %> </td>
              <% number + 1 %>
              <td > <%= link_to event.title, event_path(event) %></td>
              <td > <%= event.body %></td>
              <td > <%= event.date %></td>
              <td > <%= event.attendees.length %></td>
              <td> Placeholder to update attend status</td>
            </tr>

      <% end %>

    <% end %>
  <% end %>